# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dice_pb2 as dice__pb2


class DiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RollDice = channel.unary_unary(
                '/dice.DiceService/RollDice',
                request_serializer=dice__pb2.RollDiceRequest.SerializeToString,
                response_deserializer=dice__pb2.RollDiceResponse.FromString,
                )


class DiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RollDice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RollDice': grpc.unary_unary_rpc_method_handler(
                    servicer.RollDice,
                    request_deserializer=dice__pb2.RollDiceRequest.FromString,
                    response_serializer=dice__pb2.RollDiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dice.DiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RollDice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dice.DiceService/RollDice',
            dice__pb2.RollDiceRequest.SerializeToString,
            dice__pb2.RollDiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
