# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndice.proto\x12\x04\x64ice\"3\n\x0fRollDiceRequest\x12\x0f\n\x07min_num\x18\x01 \x01(\x05\x12\x0f\n\x07max_num\x18\x02 \x01(\x05\"\"\n\x10RollDiceResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32H\n\x0b\x44iceService\x12\x39\n\x08RollDice\x12\x15.dice.RollDiceRequest\x1a\x16.dice.RollDiceResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROLLDICEREQUEST._serialized_start=20
  _ROLLDICEREQUEST._serialized_end=71
  _ROLLDICERESPONSE._serialized_start=73
  _ROLLDICERESPONSE._serialized_end=107
  _DICESERVICE._serialized_start=109
  _DICESERVICE._serialized_end=181
# @@protoc_insertion_point(module_scope)
